"""empty message

Revision ID: 54b5996757a4
Revises: 2ae65caa2c99
Create Date: 2016-01-12 18:07:04.778919

"""

# revision identifiers, used by Alembic.
revision = '54b5996757a4'
down_revision = '2ae65caa2c99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey', 'permit_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey', 'permit_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    ### end Alembic commands ###
